name: salva2
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.1.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_walkthrough:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - foto/salva2.png
    #Colegio/Universidad Nivel 1
    - foto/cu/n1/1.png
    - foto/cu/n1/2.png
    - foto/cu/n1/3.png
    - foto/cu/n1/4.png
    - foto/cu/n1/5.png
    - foto/cu/n1/6.png
    - foto/cu/n1/7.png
    - foto/cu/n1/8.png
    - foto/cu/n1/9.png
    - foto/cu/n1/10.png
    #C/U Nivel 2
    - foto/cu/n2/1.png
    - foto/cu/n2/2.png
    - foto/cu/n2/3.png
    - foto/cu/n2/4.png
    - foto/cu/n2/5.png
    - foto/cu/n2/6.png
    - foto/cu/n2/7.png
    - foto/cu/n2/8.png
    - foto/cu/n2/9.png
    - foto/cu/n2/10.png
    #C/U Nivel 3
    - foto/cu/n3/1.png
    - foto/cu/n3/2.png
    - foto/cu/n3/3.png
    - foto/cu/n3/4.png
    - foto/cu/n3/5.png
    - foto/cu/n3/6.png
    - foto/cu/n3/7.png
    - foto/cu/n3/8.png
    - foto/cu/n3/9.png
    - foto/cu/n3/10.png
    #Casa nivel 1
    - foto/casa/n1/1.png
    - foto/casa/n1/2.png
    - foto/casa/n1/3.png
    - foto/casa/n1/4.png
    - foto/casa/n1/5.png
    - foto/casa/n1/6.png
    - foto/casa/n1/7.png
    - foto/casa/n1/8.png
    - foto/casa/n1/9.png
    - foto/casa/n1/10.png
    #Casa nivel 2
    - foto/casa/n2/1.png
    - foto/casa/n2/2.png
    - foto/casa/n2/3.png
    - foto/casa/n2/4.png
    - foto/casa/n2/5.png
    - foto/casa/n2/6.png
    - foto/casa/n2/7.png
    - foto/casa/n2/8.png
    - foto/casa/n2/9.png
    - foto/casa/n2/10.png
    #Casa nivel 3
    - foto/casa/n3/1.png
    - foto/casa/n3/2.png
    - foto/casa/n3/3.png
    - foto/casa/n3/4.png
    - foto/casa/n3/5.png
    - foto/casa/n3/6.png
    - foto/casa/n3/7.png
    - foto/casa/n3/8.png
    - foto/casa/n3/9.png
    - foto/casa/n3/10.png
    #lugaresPub nivel 1
    - foto/lugaresPub/n1/1.png
    - foto/lugaresPub/n1/2.png
    - foto/lugaresPub/n1/3.png
    - foto/lugaresPub/n1/4.png
    - foto/lugaresPub/n1/5.png
    - foto/lugaresPub/n1/6.png
    - foto/lugaresPub/n1/7.png
    - foto/lugaresPub/n1/8.png
    - foto/lugaresPub/n1/9.png
    - foto/lugaresPub/n1/10.png
    #lugaresPub nivel 2
    - foto/lugaresPub/n2/1.png
    - foto/lugaresPub/n2/2.png
    - foto/lugaresPub/n2/3.png
    - foto/lugaresPub/n2/4.png
    - foto/lugaresPub/n2/5.png
    - foto/lugaresPub/n2/6.png
    - foto/lugaresPub/n2/7.png
    - foto/lugaresPub/n2/8.png
    - foto/lugaresPub/n2/9.png
    - foto/lugaresPub/n2/10.png
    #lugaresPub nivel 3
    - foto/lugaresPub/n3/1.png
    - foto/lugaresPub/n3/2.png
    - foto/lugaresPub/n3/3.png
    - foto/lugaresPub/n3/4.png
    - foto/lugaresPub/n3/5.png
    - foto/lugaresPub/n3/6.png
    - foto/lugaresPub/n3/7.png
    - foto/lugaresPub/n3/8.png
    - foto/lugaresPub/n3/9.png
    - foto/lugaresPub/n3/10.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
